### ISSUE TITLE
Include method of simulating tabbing through

### ISSUE THREAD

**Issue by diego-codes** [testing-library/user-event#156]
I don't know if this is the best place to address this request, but I would love to have a way to simulate a user tabbing through an interface. This type of event would be helpful for testing [the keyboard focus behavior of dialogs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role#Required_JavaScript_features) for example.

This type of event allows for slightly better accessibility testing.

**Comment by weyert** [comment]
I have been thinking this might be easier to handle in Cypress with the tab plugin: https://github.com/Bkucera/cypress-plugin-tab

**Comment by Gpx** [comment]
This is a really big feature, IMO. I don't think I want to implement it in user-event. First, tabbing is implemented by the browser so your tests would have to test the browser's behavior rather than your component's. Second I see some edge cases, for example, if you test a component in isolation it might work in a certain way but when it's rendered along with other components that include `tabIndex` the tabbing would be completely different.

I don't think we can provide a reliable implementation of this feature. I agree with @weyert that testing in Cypress or other browser-based tools is the way to go.

I'm closing this issue but feel free to comment if you have any idea on how to make this work reliably in user-event.
