### ISSUE TITLE
Entering a combination of valid and invalid characters in a number input returns an empty string

### ISSUE THREAD

**Issue by alavkx** [testing-library/user-event#191]
I expect that if you type something like
```js
userEvent.type(input, "-1.0abc!@#");
```
in to a number input, `input.value` should equal "-1.0".
In this case, `input.value` equals `""`

```js
function PctInput({ onChange, value = 0, name, ...props }) {
  const format = x => significantFigures(2, decimalToPercent(x));
  const [displayValue, setDisplayValue] = React.useState(format(value));
  React.useEffect(() => {
    onChange({ [name]: percentToDecimal(displayValue) });
  }, [displayValue, onChange, name]);
  return (
    <Input
      type="number"
      name={name}
      value={displayValue}
      onChange={event => {
        setDisplayValue(event.target.value);
      }}
      {...props}
    />
  );
}

const setup = ({ value = 0, onChange = jest.fn(), ...props } = {}) => {
  const utils = render(
    <PctInput
      data-testid={"input"}
      onChange={onChange}
      value={value}
      {...props}
    />
  );
  utils.getByTestId("input").focus();
  return { input: document.activeElement || document.body, ...utils };
};

test("should only allow number inputs (0-9, -, .)", () => {
  const { input } = setup();
  userEvent.type(input, "-1.0abc!@#");
  expect(input.value).toEqual("-1.0");
});
```

```js
 FAIL  app/scripts/components/Sidebar/StepSettingsSidebar/StepChildSettingsSection/TooltipOptions/PctInput.test.js
  ● should only allow number inputs (0-9, -, .)

    expect(received).toEqual(expected) // deep equality

    Expected: "-1.0"
    Received: ""

      20 |   const { input } = setup();
      21 |   userEvent.type(input, "-1.0abc!@#");
    > 22 |   expect(input.value).toEqual("-1.0");
         |                       ^
      23 | });
      24 | test("should allow user to delete all of the characters, one at a time", () => {
      25 |   const { input } = setup({

      at Object.toEqual (app/scripts/components/Sidebar/StepSettingsSidebar/StepChildSettingsSection/TooltipOptions/PctInput.test.js:22:23)
```

**Comment by bkong88** [comment]
This is due to `async type()`having the following logic for an example string of `"12AB"`:  
Loop 1:  
    `fireEvent.input("1") // OK, input element will have value of '1' now`  
Loop 2:  
    `fireEvent.input("12") // OK, input element will have value of '2' now`  
Loop 3:  
    `fireEvent.input("12A") // Not OK, input element doesn't recognize so it has value of '' now`  
Loop 4:  
    `fireEvent.input("12AB") // Same as Loop 3`  

One easy solution is to just cover the case for when `<input type="number" />`. However, I see that `async type()` accepts a `userOpts` object. We could also allow a regex to be input into the `userOpts` object, and have each loop match only the characters allowed by the regex. This can cover any cases the developer may have.  

Example:
```javascript
async type(element, text, userOpts = {}) {
    if (element.disabled) return;
    const defaultOpts = {
      allAtOnce: false,
      delay: 0,
      acceptableChars: /./, // By default, accept every character
    };
    const opts = Object.assign(defaultOpts, userOpts);
    ...
    ....
          if (pressEvent && !isTextPastThreshold) {
            actuallyTyped += key;
            const acceptableCharsInput = findAcceptableChars(actuallyTyped, opts.acceptableChars) // This util function needs to be created
            if (!element.readOnly) _dom.fireEvent.input(element, {
              target: {
                value: acceptableCharsInput
              },
              bubbles: true,
              cancelable: true
            });
          }
        }
    ...
  }
```

Of course, as number is a common case, we could implement a conditional for when `element.tagName === "INPUT" && element.type === "number"`, then assign `opts.acceptableChars = /[0-9/`  

The most ideal solution, I think, would be to input each character one at a time. If it triggers `onChange`, then we know it is an acceptable character by this input element, and add its value to `acceptableCharsInput`. This would forego the need for regex and is more in line with `testing-library` [Guiding Principles](https://testing-library.com/docs/guiding-principles). However, I can't think of any way to check whether `onChange` has been triggered at the moment.

**Comment by kentcdodds** [comment]
We made a bunch of changes to `type`. If you could update and try things with the changes then open a new issue if there are still problems you see needing fixing, then please do so. Thanks!
