### ISSUE TITLE
Tab action does not simulate focus/blur events

### ISSUE THREAD

**Issue by jzarzeckis** [testing-library/user-event#209]
In browser when you call `focus()` or `blur()` on an element programmatically, `focusin` or `focusout` events bubble from the focused/blurred element. However in jsdom they do not.

If the application logic depends on these events, would be appropriate to simulate these events too, when calling `userEvent.tab()`, so that it's possible to test such logic in jsdom too.

**Comment by mamacdon** [comment]
Why was this closed?

Does one have to dispatch a blur event manually in order to get browser-like behavior for tabbing?

**Comment by ph-fritsche** [comment]
> Why was this closed?

Probably because the author created a false report. Perhaps he used some outdated version of `jsdom`, realized it and closed it.
Otherwise the issue would be in the scope of `jsdom` anyway.

Please don't resurrect old, closed issues just for the sake of it. If you happened to run into the same issue, please set up a reproduction case per [codesandbox.io](https://codesandbox.io). :)
