### ISSUE TITLE
Document body should be a focusable element

### ISSUE THREAD

**Issue by juanca** [testing-library/user-event#365]
- `@testing-library/user-event` version: `@testing-library/user-event@10.4.0`
- Testing Framework and version: `jest@25.1.0`
- DOM Environment: `jsdom@16.2.0`
- node: `node/10.20.1`

Relevant code or config (I'm also using React)

```javascript
it('manages the page tab sequence', () => {
  function TestComponent() {
    return (<ul role="listbox">
      <li role="option" tabindex="0">First option</li>
      <li role="option" tabindex="-1">Second option</li>
    </ul>);
  }

  render(<TestComponent />);

  expect(document.body).toHaveFocus();

  userEvent.tab();
  expect(screen.getByText('First option')).toHaveFocus();

  userEvent.tab();
  expect(document.body).toHaveFocus();

  userEvent.tab({ shift: true });
  expect(screen.getByText('First option')).toHaveFocus();
});
```

What you did:

Ran the test.

What happened:

The test failed. 

```
    expect(element).toHaveFocus()

    Expected
      <body><div><ul role="listbox"><li role="option" tabindex="0">First option</li><li role="option" tabindex="-1">Second option</li></ul></div></body>
    Received:
      <li role="option" tabindex="0">First option</li>

      76 | 
      77 |       userEvent.tab();
    > 78 |       expect(document.body).toHaveFocus();
         |                             ^
      79 | 
      80 |       userEvent.tab({ shift: true });
      81 |       expect(screen.getByText('First option')).toHaveFocus();
```

Reproduction repository:

Problem description:

It looks like the `tab` method does not consider the body as a tabable element. That is actually not true -- at least from doing a quick experiment in Chrome.

The following screenshot is the experiement. 

1. Render a button
1. Look at active element (body)
1. Press tab
1. Look at active element (button)
1. Press tab
1. Look at active element (body)

<img width="1566" alt="Screen Shot 2020-06-17 at 12 21 03 PM" src="https://user-images.githubusercontent.com/841084/84941849-c8488400-b096-11ea-8c52-3c95eb121e9a.png">

Suggested solution:

Assuming the focus trap is on the document, always set the body as the first tabable element.

**Comment by juanca** [comment]
Possibly related: 

Looks like we need to integrate `act` in `userEvent.tab`. Otherwise, we should recommend using `act` with `tab`. I noticed the user event was not waiting for my stateful component updates. I can look into reproducing this with the same example: use state to manage tab indices (focus => change indices structure).

**Comment by marcosvega91** [comment]
Hi @juanca I think that body is not in the list of focusable elements

**Comment by nickmccurdy** [comment]
I've tested this out on various macOS and Windows browsers. Whenever I press tab past the end of the document (without any focus traps), `document.activeElement` is set back to the body, but my keyboard's cursor actually goes outside of the browser viewport and into the browser chrome (including the tabs and navigation bar items). So I'm not sure if it's accurate to say that the body can be focused traditionally, but it can be the active element, and the number of times you'd have to press tabs to loop back into the beginning of the page is actually nondeterministic (as you don't know how many tabs the user has open or what browser UI buttons they have in a test).

The [MDN documentation on `activeElement`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement) seems to confirm this as well:
> When there is no selection, the active element is the page's `<body>` or `null`.

A far as I understand, `body` is not actually focusable, but it will be used by `activeElement` (if `null` isn't used in its place). We should decide if `toHaveFocus` should be replaced by something like `toBeActiveElement`, or if it should literally only emulate the behavior of focusable elements instead of emulating the `tab` key. I'm also not sure how we should handle continuing to tab past the end of the document when there's no focus trap. Should we add an arbitrary number of fake buttons, loop back around, or error because the functionality is undefined outside of a browser?

**Comment by juanca** [comment]
@nickmccurdy I appreciate the analysis and clarification. I think you're 100% right. 

Instead, I think the issue is: 

> `tab` method should not cycle unless there is a focus trap defined

Expected behavior: 

When there is no focus trap defined, the default scope of tabable elements is the `document.body`. When the tab is at the end of the page tab sequence, it sets the active element to `document.body`. 

Actual behavior:

The `tab` method focuses the first tabable element in the `document.body` when there is no user-provided focus trap. 

Suggested solution:

1. Fix `tab` method to avoid cycling given a lack of user-provided focus trap. 

Outside of scope:

1. Renaming or splitting `toHaveFocus` seems to be a problem but I think it might be an additional issue instead of the same issue. 

Whaddya'll think?

**Comment by nickmccurdy** [comment]
That sounds good.

Maybe we should just leave `toHaveFocus` alone. It's not a perfectly accurate name, but it is practical, and I think it would be too confusing to have a separate matcher for the unfocused state. Since `activeElement` is actually `body` when nothing is focused in JSDOM, I think it's fair to treat that as focused, even if it's slightly different from browser semantics.
