### ISSUE TITLE
Does this lib support <input type="color"/> ?

### ISSUE THREAD

**Issue by ambroiseRabier** [testing-library/user-event#423]
Does this lib support `<input type="color"/>` ?

**Comment by kentcdodds** [comment]
Hi @ambroiseRabier,

Yes it does.

**Comment by ambroiseRabier** [comment]
I didn't said it explicitly, but how do you use this library to set the color ? I doesn't `type` anything, when choosing a colors, it is a serie of minimum 2 clicks. Neither `click` or `type` seem to have options for colors.
I just tried the closest I could think of: `userEvent.type(element, '#123456', {delay:0})`, no success with that.

**Comment by kentcdodds** [comment]
Sorry, I think I was mistaken. Hey @visualjerk, do you have any ideas here?

**Comment by visualjerk** [comment]
`<input type="color" />` is a bit tricky, as most browsers display it as a color picker.

As you can see [here](https://codepen.io/visualjerk/pen/poyoKNN?editors=1111) typing on these doesn't trigger an input event or change the inputs value.

So in order to test those you would probably have to use `dom-testing-library` [fireEvent](https://testing-library.com/docs/dom-testing-library/api-events#fireevent) to dispatch an input event:

```js
fireEvent.input(colorInputElement, {target: {value: '#333333'}})
```

Maybe we find a solution that comes closer to how a user interacts with these kind of inputs, but I assume it is pretty hard to do inside a emulated dom.

**Comment by kentcdodds** [comment]
I agree. Maybe we could add a note in the docs about this? @ambroiseRabier, would you be interested in doing that?

**Comment by ambroiseRabier** [comment]
@visualjerk that is indeed the solution I went for.
@kentcdodds when you mean doc, you mean the README.md ? I see no section that would fit this piece of information, should we add a "Known issues" or "Unsupported user events" section ?

**Comment by kentcdodds** [comment]
Yeah, I think a new section titled "Known issues" or "Known limitations" would be useful.

**Comment by jesujcastillom** [comment]
Can I help with that?

**Comment by kentcdodds** [comment]
Sure @jesujcastillom :)

**Comment by josebui** [comment]
Is there any expectation to support this in the future?
