### ISSUE TITLE
Proposal: Add info about jest-config to documentation

### ISSUE THREAD

**Issue by visualjerk** [testing-library/user-event#425]
By default jest uses an older version of jsdom. This version misses some features (eg. fire focusout on element.blur()). So in order to get the most out of `user-event` it is best to make sure jest uses the latest jsdom version, by adding this to the config:

```js
testEnvironment: 'jest-environment-jsdom-sixteen',
```

Should we add a note about this somewhere in the README?

**Comment by kentcdodds** [comment]
We could add this to the docs, but this is actually incorrect:

> By default jest uses an older version of jsdom

What's now likely is you're using an old version of jest and if you updated jest you'd get the latest version of jsdom as well. Unfortunately a lot of people are stuck on an old version of jest because they're using react-scripts which is still pending a major release after months of delays. Any day now I expect the release to happen, but I've thought that for months now. I'm not sure what's taking so long, but once it does then this should not be a problem nearly as often and the recommendation can simply be to update to the latest version of jest or react-scripts where applicable.

**Comment by visualjerk** [comment]
You're totally right 😅 

I just assumed that because we use the latest version of `@vue/cli-plugin-unit-jest` and it has an old version of jest included as well as this in its jest preset (notice the fifteen instead of sixteen):

```js
testEnvironment: 'jest-environment-jsdom-fifteen',
```

Maybe it is enough to relate to this issue, if someone stumbles upon a similar problem. I guess having it in the docs is a bit of an overkill for an issue that happens only when using an outdated jest version.
