### ISSUE TITLE
UserEvent.type / paste does not work on material ui Input (single line)

### ISSUE THREAD

**Issue by noamantebi** [testing-library/user-event#458]
- `@testing-library/user-event` version: 12.0.4
- `@testing-library/dom` version: 7.24.3
- `@testing-library/jest-dom` version: 5.11.4
- `@testing-library/react` version 11.0.4
- `@material-ui/core` version: 3.9.3

Relevant code or config
```javascript
import { Input } from '@material-ui/core'

const MyInput:  React.FunctionComponent = () => {
  const [inputVal, setInputVal] = useState('')
  return (
    <Input
      value={inputVal}
      onChange={e => setInputVal(e.target.value)}
      data-testid='my-input'
  />)
}

test('delete characters within the selectedRange', () => {
    render(<MyInput/>)
    const input = screen.getByTestId('my-input') as HTMLInputElement
    userEvent.type(input, 'bla')

    expect(input).toHaveValue('bla')
  })

```

I have component that contains material ui  Input. 
The tests doesn't pass, and the value remains empty: 
```
Expected the element to have value:
  bla
Received:
  undefined
```

Once Im changing the Input to be multiline = true the tests pass (testing textContent instead of value)
If Im using <input> tag directly it also passed. 

What am I missing why the material UI Input does not work? Thank you.

**Comment by malwilley** [comment]
Hello @noamantebi!

I believe the issue here is what the material-ui component does with your `data-testid` prop. If you look at the rendered html, you are getting something like:

```html
<div data-testid="my-input">
  <input />
</div>
```

So the line `screen.getByTestId('my-input')` returns the containing div, not the `<input />` that we need here.

Looking at the `material-ui` docs, it looks like you can use `inputProps` to place props straight onto the input element: https://material-ui.com/api/input/

Hope this helps!

**Comment by noamantebi** [comment]
Thanks! 
Actually that was my bad not putting it in the code example. Anyway I found out that the problem was that we passed to the Input type="string" and not text as it should. That solved my problem!
Thanks for the quick reply!
