### ISSUE TITLE
"warning " > @testing-library/user-event@12.6.2" has unmet peer dependency "@testing-library/dom@>=7.21.4".

### ISSUE THREAD

**Issue by tonydehnke** [testing-library/user-event#551]
Hi, newbie here, so I will try to put as much info as I can.  This is not a problem using the package, just a warning on install.

- `@testing-library/user-event` version: 12.6.2
- node:  14.x

What you did:
   When running `yarn install` with the latest user-event version,  while linking dependencies I get the following warning:
`warning " > @testing-library/user-event@12.6.2" has unmet peer dependency "@testing-library/dom@>=7.21.4".`

From what I have read, this means that in the `user-event` package, it is missing the package as a dependency, and this should be corrected in the user-event package.  Is that correct?

**Comment by nickmccurdy** [comment]
`@testing-library/user-event` depends on `@testing-library/dom`. If `user-event` listed `dom` as a dependency, there may be multiple versions of `dom` installed which could break tests or types. To avoid this, `user-event` lists `dom` as a peer dependency. (Further explanation: https://github.com/testing-library/user-event/pull/438#issuecomment-680134095)

The solution is to install `@testing-library/dom` manually in projects that use `@testing-library/user-event`, or use a package manager that automatically installs peer dependencies (like npm 7).

**Comment by tonydehnke** [comment]
Thanks for the info and link Nick, I'll read up on it some more.

**Comment by nickmccurdy** [comment]
If that doesn't fix the error feel free to reply here or ask on Discord: https://discord.gg/testing-library

**Comment by dietergeerts** [comment]
Hi, we have this error in our rush mono-repo, but it's hard to figure out how these work in the combination of `testing-library` packages. We have the following listed currently (we are moving to a mono-repo, these where the dependencies we currently have, and do work):

```
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/react-hooks": "^5.1.2",
    "@testing-library/user-event": "^12.8.3",
```
So the `@testing-library/react` lib here has an actual dependency on `@testing-library/dom`, which makes it unavailable to any other package due to our usage of `pnpm/rush combo`. `@testing-library/user-event` is stating it as a peer-dependency, but if we would add that, it will conflict with the one stated in `@testing-library/react`.

A solution that I see is that the `@testing-library/react` package should state `@testing-library/dom` as a peerDependency too. I don't know if this is possible, or if there is some other better logic that I'm not seeing here?

**Comment by mr-bjerre** [comment]
Is it expected to get `missing peer @testing-library/dom@>=7.21.4` when I have `@testing-library/react` installed?

The issue is that `pnpm` returns error code on missing peer dependencies by default. Of course I could disable that but I think it makes sense to have that return an error. The issue here is that I'm getting told that I'm missing a dependency which I'm not actually missing. 

@nickmccurdy I did take a look at https://github.com/testing-library/user-event/pull/438#issuecomment-680134095 but I'm still not sure here.

**Comment by carlbleick** [comment]
@mr-bjerre Did you resolve the issue with pnpm?

**Comment by mr-bjerre** [comment]
> @mr-bjerre Did you resolve the issue with pnpm? 

No. However you can have pnpm return success even though there are unmet peer dependencies. Not exactly a solution but a workaround I guess
