### ISSUE TITLE
userEvent.type breaks when typing JSON

### ISSUE THREAD

**Issue by lynxtaa** [testing-library/user-event#584]
- `@testing-library/user-event` version: 13.0.0

- Testing Framework and version: jest@26.6.3

Relevant code or config

```javascript
userEvent.type(input, '{"foo":"bar"}')
```

What you did: See above

What happened:

Error: `Expected key descriptor but found """ in "{"foo":"bar"}"`

Problem description:

Possible regression? It worked in user-event@12.8.3

**Comment by ph-fritsche** [comment]
There is a new implementation for `userEvent.type` and the added `userEvent.keyboard` in [v13.0.0](https://github.com/testing-library/user-event/releases/tag/v13.0.0).

Instead of adding more and more special strings like `{arrowleft}` the new implementation treats '{' and '[' as special characters and [treats the following as a descriptor](https://github.com/testing-library/user-event#keyboardtext-options).

You can work around by escaping `{` and `[`.
```js
userEvent.type(input, '{"foo":"bar"}'.replace(/[{[]/g, '$&$&'))
```

**Comment by lynxtaa** [comment]
@ph-fritsche Maybe add an option to skip detection of key descriptors? Something like:
```js
userEvent.type(input, '{"foo":"bar"}', { skipSpecialCharacters: true })
```

**Comment by erickbelfy** [comment]
is the PR still open for this use case?
