### ISSUE TITLE
Cursor is moving after input

### ISSUE THREAD

**Issue by ogonkov** [testing-library/user-event#636]
- `@testing-library/user-event` version:
13.1.0

- Testing Framework and version:
jasmine-core@3.6.0
- DOM Environment:
  Chrome Headless 93

Relevant code or config

https://codesandbox.io/s/relaxed-waterfall-9cwk6?file=/src/__tests__/index.js

What you did:

I'm trying to test that cursor is preserved between inputs, but it seems moving after first input.

I'm rendering `<input>` with value `bar`,
Moving cursor to the start of the input,
Input `foo`

What happened:

I expect to get `foobar`, but actually get `fbaroo`

Reproduction repository:

Problem description:

Suggested solution:

**Comment by ph-fritsche** [comment]
`userEvent.type` moves the selection to the end of the value because most people expect it to do so.

You can override this per:
```js
userEvent.type(input, 'foo', { initialSelectionStart: 0, initialSelectionEnd: 0 })
```

Or you could use the `userEvent.keyboard` API. This does not click, move focus or change the selection range before typing.

**Comment by ph-fritsche** [comment]
Your codesandbox reports the input value to be `barfoo` after typing which is to be expected.
Should you really get `fbaroo` on the `input` element, please try to reproduce this.

**Comment by ogonkov** [comment]
> type(element, text, [options])
>Writes text inside an <input> or a <textarea>.

@ph-fritsche  i'm surprised that it is actually "clicked" somewhere aswell.

**Comment by ph-fritsche** [comment]
@ogonkov Just a few lines down:
> type will click the element before typing. To disable this, set the skipClick option to true.

The `userEvent.type` API has been introduced this way: As a convenience method to simulate the common events that happen if a user goes to an element and types there. It clicks and focuses the element, moves the cursor to the end of the input and starts typing.

Since `v13` there is also the `userEvent.keyboard` API. It just simulates pressing keys.
That's why it does not except an element as parameter. This also means that in your example nothing would be typed into the input because it is not the active element.

That's why the README states:
> You should use userEvent.keyboard if you want to just simulate pressing buttons on the keyboard. You should use userEvent.type if you just want to conveniently insert some text into an input field or textarea.

**Comment by ph-fritsche** [comment]
Because most people select input fields by clicking into the free area in the textbox which moves the cursor to the end of the input.
So most people go
```js
render(`<input value="foo"/>`)
userEvent.type(screen.getByRole('textbox'), 'bar')
expect(screen.getByRole('textbox')).toHaveValue('foobar')
```
Without moving focus it would be `foo` and with programmatically moving focus but not setting selection range it would be `barfoo`. Both are confusing for users because neither is what they get when they "just do it in the browser".

**Comment by ph-fritsche** [comment]
Yes, and then you call ‘userEvent.type‘ which can not know that you moved the selection from ‘0,0‘ to ‘0,0‘.
So what's your point?

**Comment by ogonkov** [comment]
Oh, i think i get it now. I was expected that `type()` will respect current cursor position, because of this

https://github.com/testing-library/user-event/blob/7143ae30353e0cc7f8f12e405763eaf2257ef03e/src/type/typeImplementation.ts#L50-L60
