### ISSUE TITLE
`hover` doesn't call events on parents if the element has `pointer-events: none`

### ISSUE THREAD

**Issue by kalley** [testing-library/user-event#646]
- `@testing-library/user-event` version: 13.1.2

- Testing Framework and version: jest@26.6.3
  
- DOM Environment: jsdom@16.4.0
  

Relevant code or config (smallest repro I could make)

```javascript
it('calls onMouseOver on hover', () => {
  const onMouseOver = jest.fn();

  render(
    <div onMouseOver={onMouseOver}>
      <div style={{ pointerEvents: 'none' }}>Target</div>
    </div>,
  );

  const target = screen.getByText(/target/i);

  userEvent.hover(target);

  // This fails, but would succeed in the browser
  expect(onMouseOver).toHaveBeenCalled();
});
```

What you did: Tried to `hover` on an element that has pointer-events: none, but it's parent does not

What happened: Hover events didn't bubble up

Reproduction repository: The above code is the minimal amount of code, but I can create a repo if necessary.

Problem description:
If you hover over an element that has `pointer-events: none`, no events bubble to parent elements even though they should.

I actually ran into this problem testing tooltips on disable list items that have a similar structure to the repro above. In the meantime, I can forcibly call `hover` on the `parentNode`.

Suggested solution:
If `pointer-events: none` is set, run `hover` on the immediate parent.

**Comment by ph-fritsche** [comment]
There is no bubbling `mouseover` on the element with `pointer-events: none`.
The `pointer-events: none` element is ignored and if the parent is behind it, the pointer events falls through to it. But there could be any other element between them or they don't overlap at all.
`userEvent` is developed with jest+jsdom in mind and there is no layout so no way for `userEvent` to determine what element would receive the pointer event instead of your target.

See https://codesandbox.io/s/keyevent-forked-8tkpk?file=/src/App.js

**Comment by kalley** [comment]
@ph-fritsche Thank you for the detailed reasoning. That makes perfect sense and I hadn't even thought about elements that were absolutely positioned or otherwise taken outside the normal flow.
