### ISSUE TITLE
userEvent.click calls mock function twice 

### ISSUE THREAD

**Issue by codepath2019** [testing-library/user-event#655]
Hi, this is my first time opening an issue on github issues. Thank you to testing-library team in advance for taking a look at my issue here. I believe this is a bug and would appreciate your help in understanding how to move forward on this issue.

### Configuration
```js
{
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^13.1.3",
}
```

### Relevant Code
```js
// Selectbox.js
import React from 'react';
import { map } from 'ramda';

const Selectbox = ({ onClick, menuItems }) => (
  map(
    menuItem => (
      <label onClick={onClick}>
        {menuItem.labelText}
        <input
          type="radio"
          value={menuItem.value}
        />
      </label>
    ),
    menuItems,
  )
);

export default Selectbox
```

```js
// Selectbox.spec.js
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import Selectbox from './Selectbox';
describe('Selectbox', () => {
  const mockOnClick = jest.fn()
  const menuItems = [
    {
      labelText: "Space Pony",
      value: "spacePony",
    },
    {
      labelText: "Unicorn Tail",
      value: "unicornTail",
    },
  ];

  beforeEach(() => {
    render(
      <Selectbox
        onClick={mockOnClick}
        menuItems={menuItems}
      />
    )
  })

  it('can be clicked', () => {
    userEvent.click(screen.getByText(menuItems[0].labelText))
    expect(mockOnClick).toHaveBeenCalledTimes(1)
  })
})
```

### Expectation
I expect that the `mockOnClick` function would only be caled once

### Actual
The `mockOnClick` function was called twice

<img width="400" alt="Screen Shot 2021-04-18 at 12 10 19 AM" src="https://user-images.githubusercontent.com/49729798/115137342-76d09480-9fda-11eb-86bf-cb6344fbbebe.png">

### Reproduction repository
https://github.com/codepath2019/user-event-bug-report

**Comment by codepath2019** [comment]
<img width="817" alt="Screen Shot 2021-04-18 at 12 10 19 AM" src="https://user-images.githubusercontent.com/49729798/115137342-76d09480-9fda-11eb-86bf-cb6344fbbebe.png">

**Comment by ph-fritsche** [comment]
The second `click` is to be expected and happens in the browser too.
When you `click` a `label`, a `click` is dispatched on the associated form control.
Since you nested the `input` in the `label` you receive two `click` events on the `label`. The first for your `click` on the `label` and the second `click` is bubbling up from `input`.
See https://codesandbox.io/s/trusting-mclaren-clwmy?file=/src/App.js

Side notes:
* You probably want to use `screen.getByLabelText` or `screen.getByRole` to click the radio.
  See https://codesandbox.io/s/trusting-mclaren-clwmy?file=/src/Selectbox.spec.js
* You probably want to use `onChange` handler on the input instead of handling clicks yourself.

**Comment by codepath2019** [comment]
Hey @ph-fritsche, thank you so much for responding so promptly! I will take a crack at this tomorrow.
