### ISSUE TITLE
Events on Vue components call associated methods, but don't update DOM unless awaited

### ISSUE THREAD

**Issue by rydash** [testing-library/user-event#659]
Hello! I'm a big fan of `user-event` in my React projects, and I know that's the primary framework for this library! I've started learning Vue and want to use userEvent in my component tests here too, but weird stuff happens. I'll do my best to describe what I think is going on; please be patient with me!

- `@testing-library/user-event` version: 13.1.5
- Testing Framework and version: Jest 26.6.3 (with jest-dom matchers 5.11.10)
- DOM Environment: jsdom 16.5.2
- Vue version: 2.6.12

Relevant code or config

_Component_
```vue
// Header.vue
<template>
<div>
    <h1 v-if="checked">
        Checked
    </h1>
    <h1 v-else>
        Unchecked
    </h1>
    <fieldset>
        <legend class="question">Check this box to make the header change!</legend>
        <input
            id="box"
            type="checkbox"
            v-on:change="toggleBox()"
        >
        <label for="box">Click me!</label>
    </fieldset>
</div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
    data() {
        return {
            checked: false
        }
    },

    methods: {
        toggleBox() {
            this.checked = !this.checked
        }
    }
})
</script>
```

_Failing test_
```ts
// Header.test.ts
import { render, screen } from '@testing-library/vue'
import userEvent from '@testing-library/user-event'

import Header from './Header.vue'

test('changes the header when checkbox checked', () => {
    render(Header)

    userEvent.click(screen.getByLabelText('Click me!'))
    
    // passes
    expect(screen.getByLabelText('Click me!')).toBeChecked()

    // fails
    expect(screen.getByText('Checked')).toBeInTheDocument()
})

// screen.debug() output
<body>
  <div>
    <div>
      <h1>
        Unchecked!
      </h1>
      <fieldset>
        <legend
          class="question"
        >
          Check this box to make the header change!
        </legend>
        <input
          id="box"
          type="checkbox"
        />
        <label
          for="box"
        >
          Click me!
        </label>
      </fieldset>
    </div>
  </div>
</body>
```

_Working test without user-event_
```ts
// Header.test.ts
import { fireEvent, render, screen } from '@testing-library/vue'

import Header from './Header.vue'

test('changes the header when checkbox checked', async () => {
    render(Header)

    await fireEvent.click(screen.getByLabelText('Click me!'))

    // passes
    expect(screen.getByLabelText('Click me!')).toBeChecked()
    expect(screen.getByText('Checked')).toBeInTheDocument()
})

// screen.debug
<body>
  <div>
    <div>
      <h1>
        Checked!
      </h1>
      <fieldset>
        <legend
          class="question"
        >
          Check this box to make the header change!
        </legend>
        <input
          id="box"
          type="checkbox"
        />
        <label
          for="box"
        >
          Click me!
        </label>
      </fieldset>
    </div>
  </div>
</body>
```

_Working test, unexpectedly, with user-event_
```ts
// Header.test.ts
import { render, screen } from '@testing-library/vue'
import userEvent from '@testing-library/user-event'

import Header from './Header.vue'

test('changes the header when checkbox checked', async () => {
    render(Header)

    // user-event should be synchronous, so why does this work?
    await userEvent.click(screen.getByLabelText('Click me!'))

    // passes
    expect(screen.getByLabelText('Click me!')).toBeChecked()
    expect(screen.getByText('Checked')).toBeInTheDocument()
})

// screen.debug output same as previous test
```

Reproduction repository:
I can try to get one together if the above code is not enough! It'll take me some time, though.

Problem description:
`user-event` properly interacts with DOM elements and triggers a Vue component's methods, but testing-library's representation of the DOM after that method is called doesn't change unless `userEvent.[method]` is awaited, despite the `click` method here being synchronous.

I'm not sure how to keep exploring this, and `fireEvent` is a fine substitute for now, but I figured you'd like to know this is happening with Vue!

**Comment by rydash** [comment]
Welp, [this fireEvent portion of @testing-library/vue's docs](https://testing-library.com/docs/vue-testing-library/api#fireevent) seems relevant. 😅
> Because Vue applies DOM updates asynchronously during re-renders, the fireEvent tools are re-exported as async functions. To ensure that the DOM is properly updated in response to an event in a test, it's recommended to always await fireEvent.

userEvent methods are exported synchronously, but `await`ing it will permit the DOM update! Except...if you're using `typescript-eslint`, for instance, this can trigger [its `await-thenable` rule.](https://github.com/typescript-eslint/typescript-eslint/blob/v4.22.0/packages/eslint-plugin/docs/rules/await-thenable.md)

I'm gonna keep looking for a way to correctly wait for a DOM update...this issue might not involve `user-event` as much as I thought, but it could be nice if these methods could do that waiting on my (lazy) behalf.

**Comment by vandor** [comment]
I came here in response to a similar situation (used user-event in React), and in switching to Vue I had a failing test similar to yours. I also then rediscovered the part of the Vue docs on testing that you referenced. It makes makes me wonder if this is just a normal speed bump in developers coming to Vue from React, since Vue's re-renders are async.

From reading some of the open issues in this repo (particularly #504) as well the discussion it references on merging user-event into the core of testing-library (testing-library/dom-testing-library#616), it seems that there is a big question and some disagreement about what the API of user-event should be if it aims to accommodate frameworks like Vue which render updates asynchronously.

My personal takeaways as a developer who is onboard with the testing-library guiding principle and also wants to consistently test with user-event: Using `await Vue.nextTick()` in my tests is an explicit way of acknowledging that Vue's re-renders are asynchronous. I do think it looks ugly, though, which makes me reach for user-event less -- mainly in situations when using `fireEvent` doesn't provide enough confidence.

**Comment by ph-fritsche** [comment]
> I'm gonna keep looking for a way to correctly wait for a DOM update...this issue might not involve `user-event` as much as I thought, but it could be nice if these methods could do that waiting on my (lazy) behalf.

The problem is that we wouldn't know what to wait for, the desired change could happen instantly, on the next tick, a second later or never.

But it might be a reasonable solution to just return a `Promise` on all our APIs.
Those working with frameworks rendering synchronous like React might then `await` or `void` the `Promise`, it doesn't matter.
Those working e.g. with Vue could `await` the `Promise` and while we can not ensure that the desired change happened, it will probably work 100% of the time.

See https://github.com/testing-library/user-event/issues/504#issuecomment-800651441

**Comment by rydash** [comment]
That ideology makes sense to me! For my immediate purposes, calling `userEvent.anything()` synchronously, then calling `await Vue.nextTick()` like @vandor helpfully suggests does the trick, though I see how that is hyper-specific to this framework and use case.

I don't want this issue to dilute the discussion in #504, but I'm also shy to close this in case that 'needs specification' label means there's other work/cataloging to do here.

**Comment by ITenthusiasm** [comment]
@rydash You may be able to get a clearer idea of how the problem arises from [here](https://github.com/ITenthusiasm/synchronous-vue-testing-library).

For your immediate purposes, I'd recommend using `waitFor` instead. There are peculiar circumstances where `Vue.nextTick` doesn't do what one would expect or hope for. By contrast, `waitFor` is _guaranteed_ to work in all circumstances (because you're waiting for a condition to be met). And the last assertion in your test that appears in a `waitFor` doesn't need to be `await`ed -- if that makes sense.

**Comment by rydash** [comment]
`waitFor` (along with some awaiting `screen.findBy...`) dropped in quite nicely for my use case, and the philosophy behind those methods is compelling. I like worrying about frameworks in my test code less, so thank you for highlighting that method!

**Comment by rydash** [comment]
For anyone reading this issue later, here's `waitFor` used in the test in the initial example. Both expectations pass!
```ts
import { render, screen, waitFor } from '@testing-library/vue'
import userEvent from '@testing-library/user-event'

import Header from './Header.vue'

test('changes the header when checkbox checked', async () => {
    render(Header)

    userEvent.click(screen.getByLabelText('Click me!'))

    expect(screen.getByLabelText('Click me!')).toBeChecked()
    await waitFor(() => expect(screen.getByText('Checked')).toBeInTheDocument())
})
```
