### ISSUE TITLE
userEvent.tab does not preserve focus set in onBlur event handlers

### ISSUE THREAD

**Issue by martinoconnor** [testing-library/user-event#720]
- `@testing-library/user-event` version: 12.1.10

- Testing Framework and version: @testing-library/jest-dom 5.11.4 @testing-library/react 11.1.0
  
- DOM Environment: jsdom 16.4.0
  

Relevant code or config

```javascript
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

function App() {
  return (
      <>
        <label htmlFor="one">One</label>
        <input id="one" name="one" onBlur={(e) => e.target.focus()}/>
        <label htmlFor="two">Two</label>
        <input id="two" name="two"/>
      </>
  );
}

test('focus', () => {
  render(<App />);
  const one = screen.getByLabelText('One');
  expect(one).not.toHaveFocus();
  userEvent.tab()
  expect(one).toHaveFocus();
  userEvent.tab();
  expect(one).toHaveFocus(); //Fails here
});
```

What you did:
In a browser such as Chrome, tabbing twice will end up with the first input retaining focus

What happened:

userEvent.tab() did not accurately simulate the interaction between the browser and the onBlur event within React

Problem description:
userEvent changes focus too late and does not capture any changes to focus made by event handlers

Suggested solution:
capturing focus before and after the event and only updating focus if it had not changed due to an event handler

**Comment by ph-fritsche** [comment]
We move the focus per [`HTMLElement.focus()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus).
This does also trigger the `blur` event.

We need to check if programmatically moving the focus is subject to that `onBlur` handler in the browser. If it is, this issue probably belongs at `jsdom`.

If it is not, we need to change our `focus` implementation and change `activeElement` and dispatch the `FocusEvent`s for `blur`, `focus`, `focusin` and `focusout` ourselves so that we can act on them.

**Comment by ph-fritsche** [comment]
This issue belongs with `jsdom`.
https://codesandbox.io/s/jsdom-blurhandler-2l0vq
