### ISSUE TITLE
Not behaving the same as fireEvent when clicking and changing

### ISSUE THREAD

**Issue by TrueWill** [testing-library/user-event#721]
Similar to https://github.com/testing-library/user-event/issues/696

- `@testing-library/user-event` version:

"@testing-library/user-event": "^13.1.9",

- Testing Framework and version:

Jest 26

Relevant code or config

This fails:

```javascript
const input = screen.getByLabelText(label);
input.click();
userEvent.type(input, '4');
expect(input).toHaveValue(4);
```

This passes:

```javascript
const input = screen.getByLabelText(label);
fireEvent.click(input);

act(() => {
  fireEvent.change(input, { target: { value: '4' } });
});

expect(input).toHaveValue(4);
```

But gives a "not wrapped in act" warning.

I can't provide the full code (Formik, etc.) but basically it's an `input` control with an onInput handler that restricts max length to 1 and an onClick handler that calls `e.target.select()`. I'm trying to test that, if the user clicks on the input, it'll select the default value (0) and allow them to type over it (which it does in the browser).

Render looks like:

```javascript
    render(
      <Formik initialValues={{ [fieldName]: 0 }} onSubmit={() => {}}>
        {() => (
          <Form>
            <IntegerInput name={fieldName} label={label} maxLength={1} />
          </Form>
        )}
      </Formik>
    );
```

**Comment by ph-fritsche** [comment]
This issue lacks information to reproduce so there is not much we can do about this.

A few guesses/hints you could consider:
* `Formik` is known for asynchronous state changes. Maybe the changes don't happen in the timeframe or order you expect.
* `<input type="number">` has no `maxLength` attribute.
* `<input type="number">` does not support `selectionRange`

`fireEvent` just dispatches the event with the properties you supply. So if you tell it to fire a `change` event with a given `event.target.value` it just does so.

`userEvent` calculates and dispatches the events that *might* lead up to the same `change` event. But there is a lot happening before this that might suppress this event or lead to a whole different state of the document than you expect.
This makes it so great for functional testing because it can also highlight bugs you didn't expect to be there. ;)
But it might also be that the expectation you "formulated" in your test does *not exactly* match the perceived behavior when manually testing. E.g. some changes not happening instantly but `1ms` later.
