### ISSUE TITLE
onKeyDown charCode/keyCode/which is 0

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [testing-library/user-event#842]
- `@testing-library/user-event` version: a5ca2e4
- Testing Framework and version: NA
- DOM Environment: NA

### Problem description

Adding the following test to `src/keyboard/keyboardAction.ts`

```javascript
test('trigger Synthetic `keydown` event for printable characters', async () => {
  const onKeyDown = jest.fn<unknown, [React.KeyboardEvent]>()
  render(<input onKeyDown={onKeyDown} />)
  screen.getByRole('textbox').focus()

  await userEvent.keyboard('a')
  expect(onKeyDown).toHaveBeenCalledTimes(1)
  expect(onKeyDown.mock.calls[0][0]).toHaveProperty('charCode', 65)

  await userEvent.keyboard('[Enter]')
  expect(onKeyDown).toHaveBeenCalledTimes(2)
  expect(onKeyDown.mock.calls[1][0]).toHaveProperty('charCode', 13)
})
```

yields the error

```
    trigger Synthetic `keydown` event for printable characters

    expect(received).toHaveProperty(path, value)

    Expected path: "charCode"

    Expected value: 65
    Received value: 0

      43 |   await userEvent.keyboard('a')
      44 |   expect(onKeyDown).toHaveBeenCalledTimes(1)
    > 45 |   expect(onKeyDown.mock.calls[0][0]).toHaveProperty('charCode', 65)
         |                                      ^
      46 |
      47 |   await userEvent.keyboard('[Enter]')
      48 |   expect(onKeyDown).toHaveBeenCalledTimes(2)

      at Object.<anonymous> (tests/react/keyboard.tsx:45:38)
```

Testing only `[Enter]` yields the same error. Found this while having trouble with my tests because UI relies on the `charCode` of `keydown` events. Expected?

The [MDN docs on `keyDown`](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event) hint at the fact that codes should be present, but I do not know the specs. Missing implementation? I can help with providing a fix.

### Suggested solution

Some patch was made to `keypress` to fix a similar issue (see 55e194aa96c31844950fa5c74c5ff14a513f0f24).
Similar patch should probably be made to `keyup` and `keydown` too, although the key mapping is not the same.

**Comment by ph-fritsche** [comment]
[`KeyboardEvent.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is deprecated. You should use [`KeyboardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead.

[`KeyboardEvent.charCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) is non-standard and deprecated. You should use [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) instead.

[`UIEvent.which`](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) is non-standard. You should use `KeyboardEvent.key`, `KeyboardEvent.code` or [`MouseEvent.button`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button).

We removed support for deprecated features, as we neither want to maintain features that nobody should use, nor want to encourage their usage.
We only apply `charCode` on the `keypress` because the React implementation still relies on it and behaves differently if the value is `0`. We will remove support for this when React updates their implementation.

**Comment by make-github-pseudonymous-again** [comment]
That's perfectly understandable. Thanks.

**Comment by coltanium13** [comment]
Did anyone figure out how to use userEvent.keyboard('[Enter]') in v14? i cant get the 'Enter' key to work for the life of me. It seems like the keyCode for 'Enter' is still just keyboard('[Enter]') right? or is the 'Enter' just broken in v14? i have gotten '[Space]' to work though...
