### ISSUE TITLE
Pointer Events check sometimes returns false positives

### ISSUE THREAD

**Issue by MattyBalaam** [testing-library/user-event#922]
### Reproduction example

https://codesandbox.io/s/exciting-fire-b1ibfk?file=/src/App.test.js

### Prerequisites

If you run a `userEvent.click` on an element which then has `pointer-events: none` added after the interaction, then the next `userEvent.click`on a different element thinks the element inherits `pointer-events: none`

### Expected behavior

`userEvent.click` should not throw a warning.

### Actual behavior

Error thrown “Unable to perform pointer interaction as the element has or inherits pointer-events set to "none".”

### User-event version

14.0.4

### Environment

See sandbox, which is using React 18. I also see the issue in React 17 locally.

**Comment by ph-fritsche** [comment]
Thank for the report. :heart: 

Looks like this is not a false-positive for the other element. The implicit movement of the cursor out of the previously hovered element (that now has `pointer-events: none`) triggers the error.
Replacing the `user.click` with `userEvent.click`, i.e. starting a new "session", works, because it considers the pointer to be at `document.body`.

I think first of all we should improve the error message and report the `target` element as well as the element which has `pointer-events: none`.

Then we should probably not throw an error but just skip the events if the `target` was not explicitly mentioned in the API call, i.e. `click(elX)` should only throw if `elX` receives no pointer events. Removing the check for previous position might be a mistake though, because `unhover(elX) should probably still throw.

**Comment by stefan2718** [comment]
For other users hitting this issue, I've worked around it by updating my config to ignore the hover events
```js
const user = userEvent.setup({ skipHover: true });
```

**Comment by desmond-tuiyot** [comment]
> For other users hitting this issue, I've worked around it by updating my config to ignore the hover events
> 
> ```js
> const user = userEvent.setup({ skipHover: true });
> ```

My `userEvent` import doesn't have any property like `setup`. How does this solution work exactly?

**Comment by ph-fritsche** [comment]
@all-contributors add @MattyBalaam bug

**Comment by rotimidokun** [comment]
I changed my approached based on @ph-fritsche first comment 
from `await user.click(element)` to declaring element as variable and calling `element.click()`

works for me.

**Comment by EEBK99** [comment]
@rotimidokun please share your code or test case snippet.

**Comment by rotimidokun** [comment]
@EEBK99 i don't remember where i wrote that code, but it looks something like this 

`const element = getByRole('button', {name: "test"})`

Instead of `await userEvent.click(element)`

I used `element.click()`

**Comment by ph-fritsche** [comment]
This is not a good replacement for `userEvent.click` - see [this post](https://ph-fritsche.github.io/blog/post/why-userevent) on why you should use the `user-event` Api.
If you use the latest version of `user-event` and have problems, please file an issue with a reproduction example.

**Comment by rotimidokun** [comment]
okay, thanks. @ph-fritsche

**Comment by quickEscape** [comment]
I still have the issue in 14.4.3

**Comment by Lokua** [comment]
I also have this issue in 14.5.1. Unfortunately I do not have capacity to add a repro right now.

**Comment by ffjdm** [comment]
I have the issue in 16.0.0

**Comment by supuwoerc** [comment]
+1

**Comment by oleksandr-danylchenko** [comment]
We still experience this issue even with the `pointerEventsCheck: PointerEventsCheckLevel.EachTrigger` in place!
