### ISSUE TITLE
userEvent.click option that disables throwing an error

### ISSUE THREAD

**Issue by Surm4** [testing-library/user-event#974]
### Problem description

Hey, I've been testing some component checking if `onClick` prop has not been called but I can't do that because userEvent.click is throwing an error.

```
it('... is disabled', async () => {
const onClick = jest.fn()
renderSomeComponent({ onClick, disabled: true }) // `disabled` prop applies 'pointer-events: none' rule to the styles

await userEvent.click(element) // throws error that element has 'pointer-events: none' rule applied

expect(onClick).not.toHaveBeenCalled()
})
```

I know I can check the style of element e.g. `.toHaveStyle({pointerEvents: 'none'})` but I think `expect(onClick).not.toHaveBeenCalled()` is more readable and developer friendly

### Suggested solution

Perharps `{skipThrowError: boolean}` option should be added to the userEvent.click method?
 e.g. `await userEvent.click(element, {skipThrowError: true})` // does not throw errror if can't click element

**Comment by ph-fritsche** [comment]
We believe throwing an error is the correct choice because the behavior you request with `userEvent.click(elementWithoutPointerEvents)` is undefined.
You can read more about this here: https://github.com/testing-library/user-event/issues/639#issuecomment-824863693

If you want to assert an element to not be clickable you can do so by expecting an error:
```js
await expect(() => user.click(elementWithoutPointerEvents)).rejects.toThrow(/pointer-events: none/)
```
